name: deploy infra and app to azure
on: 
  workflow_dispatch:
  push:
    branches:
      - main
env:
  NODE_VERSION: 14.x
jobs:
  validate-credentials:
    name: Validate azure credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: log out of azure
        run: |
          az logout
  
  build-infrastructure:
    name: Build infrastructure
    runs-on: ubuntu-latest
    needs: validate-credentials
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: build-infrastructure
        run: |
              az deployment group create \
                --resource-group 'IacCodeAlong' \
                --template-file './infra/main.bicep' \
                --parameters '@./infra/main.parameters.json' 

  build-and-deploy-app:
    name: build and deploy react app
    needs: build-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Use node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install and build
        run: |
          cd frontend 
          npm install
          npm run build

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: zip files
        run: |
          cd frontend/build
          zip -r ../build.zip .
      
      - name: deploy to azure web app
        id: deploy-to-web-app
        run: |
          az webapp deployment source config-zip \
            --resource-group 'IacCodeAlong' \
            --name 'DrakeHasTheBestTickTackToeApp' \
            --src frontend/build.zip
